/**
 * Aptly API
 * The swiss army knife for Debian repository management
 *
 * OpenAPI spec version: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PublishedRepository {
    /**
     * storage kind (empty for local filesystem, s3 for S3 and swift for Swift)
     */
    "storage"?: string;
    /**
     * publishing prefix, . for root
     */
    "prefix"?: string;
    /**
     * distribution name
     */
    "distribution"?: string;
    /**
     * type of published repository; snapshot for snapshot, local for local repositories
     */
    "sourceKind"?: string;
    /**
     * list of sources, Component and Name of local repository/snapshot
     */
    "sources"?: Array<models.PublishSource>;
    /**
     * list of architectures published, e.g. [\"i386\", \"amd64\"]
     */
    "architectures"?: Array<string>;
    /**
     * value of Label; field in published repository stanza
     */
    "label"?: string;
    /**
     * value of Origin; field in published repository stanza
     */
    "origin"?: string;
}

