/**
 * Aptly API
 * The swiss army knife for Debian repository management
 *
 * OpenAPI spec version: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PublishRepository {
    /**
     * required, source kind; local for local repositories and snapshot for snapshots
     */
    "sourceKind"?: PublishRepository.SourceKindEnum;
    /**
     * required, list of Component/Name objects, Name is either local repository or snpashot name
     */
    "sources"?: Array<models.PublishSource>;
    /**
     * distribution name, if missing aptly would try to guess from sources
     */
    "distribution"?: string;
    /**
     * value of Label; field in published repository stanza
     */
    "label"?: string;
    /**
     * value of Origin; field in published repository stanza
     */
    "origin"?: string;
    /**
     * when publishing, overwrite files in pool/ directory without notice
     */
    "forceOverwrite"?: boolean;
    /**
     * override list of published architectures
     */
    "architectures"?: Array<string>;
    "signing"?: models.SigningOptions;
}

export namespace PublishRepository {
    export enum SourceKindEnum {
        Local = <any> 'local',
        Snapshot = <any> 'snapshot'
    }
}
