/**
 * Aptly API
 * The swiss army knife for Debian repository management
 *
 * OpenAPI spec version: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Repository {
    /**
     * local repository name
     */
    "name"?: string;
    /**
     * text describing local repository, for the user
     */
    "comment"?: string;
    /**
     * default distribution when publishing from this local repo
     */
    "defaultDistribution"?: string;
    /**
     * default component when publishing from this local repo
     */
    "defaultComponent"?: string;
}

