/**
 * Aptly API
 * The swiss army knife for Debian repository management
 *
 * OpenAPI spec version: 0.9.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface SnapshotFromPackageRefs {
    /**
     * snapshot name
     */
    "name"?: string;
    /**
     * free-format description how snapshot has been created
     */
    "description"?: string;
    /**
     * list of source snapshot names (only for tracking purposes)
     */
    "sourceSnapshots"?: Array<string>;
    /**
     * list of package keys which would be contents of the repository
     */
    "packageRefs"?: Array<string>;
}

