version: "2"

services:
  ui:
    image: node:7.5.0
    command: npm run serve
    working_dir: /usr/src/app
    expose:
      - "3000"
    volumes:
      - ..:/usr/src/app

  api:
    build: ./api
    expose:
      - "80"

  gateway:
    build: ./gateway
    links:
      - api
      - ui
    ports:
      - "80:80"

  code-gen:
    build: ./code-gen
    command: generate -c swagger.conf.json -i swagger.yaml -l typescript-angular -o src/app/aptly/gen/gen
    working_dir: /usr/src/app
    volumes:
      - ..:/usr/src/app

  test:
    image: node:7.5.0
    command: npm run test
    working_dir: /usr/src/app
    expose:
      - "3000"
    volumes:
      - ..:/usr/src/app
